Repository GatorEducator/execexam, pull requests merged in 2024-11, with the labels that each got.

#38 feat/fix: Add Additional Testing Files and Fix the Coverage Menu for Execexam
  .coveragerc
  .github/workflows/build.yml
  .gitignore
  README.md
  coverage.json
  poetry.lock
  pyproject.toml
  pytest.ini
  scripts/badges.py
  tests/test_advise.py
  tests/test_convert.py
  tests/test_debug.py
  tests/test_display.py
  tests/test_enumerations.py
  tests/test_extract.py
  tests/test_main.py
  tests/test_pytest_plugin.py
  tests/test_util.py
Labels: test, infrastructure

#43 fix: Update Issue Templates to be Selectable on GitHub
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: bug, infrastructure

#22 feat: Add Exception Handling for LiteLLM
  execexam/advise.py
  execexam/exceptions.py
  tests/test_exceptions.py
Labels: bug, enhancement

#54 feat: Refactor --tldr Flag and Repair Test Suite
  .gitignore
  coverage.json
  execexam/display.py
  execexam/main.py
  pyproject.toml
  tests/test_main.py
Labels: enhancement
